import './Common'

default_platform(:android)

ANDROID_BUILD_GRADLE_PATH = "./android/app/build.gradle".freeze

platform :android do  
  lane :build do
    gradle(
      project_dir: 'android',
      task: "clean bundleRelease",
      properties: {
        "distribution" => "internal",
        "signingConfig" => "release"
      }
    )
  end

  lane :bump do
    current_version = get_package_version()
    new_version_name = get_new_version_number(current_version)

    android_set_version_name(
      version_name: new_version_name,
      gradle_file: ANDROID_BUILD_GRADLE_PATH
    )

    set_new_version_to_package_json(new_version_name)

    previous_build_number = google_play_track_version_codes(
      track: "internal",      
    )[0]

    android_set_version_code(
      version_code: previous_build_number + 1,
      gradle_file: ANDROID_BUILD_GRADLE_PATH
    )
  end

  lane :upload do |options|
    aab = options[:path] || './android/app/build/outputs/bundle/release/app-release.aab'

    upload_to_play_store(
      track: 'internal',
      release_status: 'draft',
      aab: aab
    )    
  end

  lane :git do
    git_commit()
    git_push()
  end
end
