name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - run: bundle install

      - name: Download Android aab artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: android-release
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          path: ./artifacts

      - name: Download Google Play service account JSON file
        env:
          GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: ${{secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON}}
        run: |
          echo "${GOOGLE_PLAY_SERVICE_ACCOUNT_JSON}" > android/google-play-service-account.json

      - name: Upload Android release
        run: |
          bundle exec fastlane android upload path:./artifacts/app-release.aab
