name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repoQsitory
        uses: actions/checkout@v4

      - name: Download Bluefin keystore base 64
        env:
          ANDROID_KEYSTORE_BASE64: ${{secrets.ANDROID_KEYSTORE_BASE64}}
        run: |
          echo "${ANDROID_KEYSTORE_BASE64}" | base64 --decode > android/app/bluefin.keystore

      - name: Create .env file
        run: |
          echo "BLUEFIN_BASE_URL=${{ secrets.BLUEFIN_BASE_URL }}" >> .env
          echo "DECRYPT_KEY=${{ secrets.DECRYPT_KEY }}" >> .env

      - name: Install dependencies
        run: |
          yarn install

      - name: Run lint
        run: |
          yarn lint

      - name: Android Bump new version
        run: |
          bundle exec fastlane android bump

      - name: Android build
        run: |
          bundle exec fastlane android build

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Git commit new bump
        run: |
          bundle exec fastlane android git

      - name: Upload Android aab artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: ./android/app/build/outputs/bundle/release/app-release.aab
